baseurl = "http://mistagiggles.github.io/"
languageCode = "en-us"
title = "MistaGiggles"

enableLandingPage = true
landingPageRedirectUrl = "/about/"
AuthorName = "Matt Shepherd"

[taxonomies]
    tag = "tags"