baseurl = "http://mistagiggles.github.io/"
languageCode = "en-us"
title = "MistaGiggles"

[params]
    author_name = "Matt Shepherd"
    twitter_username = "mista_giggles"

[taxonomies]
    tag = "tags"